import time
import numpy as np

from gaussian_models import (
    mle_onebit,
    pair_glr_onebit,
    pair_glr_full_gaussian,
    onebit_theorem_boundary,
    common_experimental_boundary,
)
from oracles import solve_regularized_shared_qp
from streams import GaussianArmStreams


def _sample_from_discrete(rng, grid, weights):
    weights = np.asarray(weights, dtype=float)
    s = weights.sum()
    if s <= 1e-15:
        return float(rng.choice(grid))
    p = weights / s
    return float(rng.choice(grid, p=p))


def run_onebit_shared_top_two(
    mu,
    delta=0.05,
    beta=0.5,
    sigma=1.0,
    param_bounds=(-2.0, 1.0),
    q_bounds=(-2.0, 1.0),
    q_grid_size=31,
    x_grid_size=61,
    challenger="TCI",
    max_rounds=20000,
    oracle_period=20,
    reg_scale=0.02,
    reg_power=0.10,
    boundary="theorem",
    seed=0,
    record_every=25,
):
    """
    Gaussian one-bit shared Top-Two simulation.

    Numerical approximations:
      * q and alternative x are discretized in the shared oracle;
      * the regularization schedule is practical: lambda_n = reg_scale*n^{-reg_power};
      * the oracle is recomputed every `oracle_period` rounds.

    The learner stores only (q,Y) for the one-bit algorithm; X is generated by
    the simulator and immediately discarded after Y=1{X>=q} is formed.
    """
    t0 = time.perf_counter()
    rng = np.random.default_rng(seed + 987654321)
    mu = np.asarray(mu, dtype=float)
    streams = GaussianArmStreams(mu, sigma=sigma, seed=seed)
    K = len(mu)
    true_best = int(np.argmax(mu))

    q_grid = np.linspace(q_bounds[0], q_bounds[1], q_grid_size)
    x_grid = np.linspace(param_bounds[0], param_bounds[1], x_grid_size)

    qs = [[] for _ in range(K)]
    ys = [[] for _ in range(K)]
    counts = np.zeros(K, dtype=int)
    mle = np.full(K, 0.5 * (param_bounds[0] + param_bounds[1]), dtype=float)

    # Initialization: one pull per arm at the midpoint threshold.
    q_init = 0.5 * (q_bounds[0] + q_bounds[1])
    n = 0
    for k in range(K):
        x = streams.sample(k)
        y = int(x >= q_init)
        qs[k].append(q_init)
        ys[k].append(y)
        counts[k] += 1
        n += 1
        mle[k] = mle_onebit(qs[k], ys[k], param_bounds, sigma)

    oracle = None
    oracle_z = None
    last_oracle_n = -10**9
    last_oracle_best = None

    history = {
        "n": [], "leader": [], "counts_prop": [],
        "mle": [], "min_glr_over_n": [], "oracle_w": [],
    }

    def get_pair_glrs(leader):
        vals = {}
        for j in range(K):
            if j == leader:
                continue
            vals[j] = pair_glr_onebit(
                leader, j, mle, qs, ys, param_bounds, sigma
            )
        return vals

    stopped = False
    recommendation = int(np.argmax(mle))
    stopping_stat = 0.0

    while n < max_rounds:
        leader = int(np.argmax(mle))
        pair_glr = get_pair_glrs(leader)
        stopping_stat = min(pair_glr.values())

        if boundary == "theorem":
            c = onebit_theorem_boundary(
                n, delta, K, param_bounds, q_bounds, sigma
            )
        else:
            c = common_experimental_boundary(n, delta, K)

        if stopping_stat >= c:
            stopped = True
            recommendation = leader
            break

        # TC / TCI challenger
        scores = {}
        for j, w in pair_glr.items():
            if challenger.upper() == "TCI":
                scores[j] = w + np.log(max(counts[j], 1))
            else:
                scores[j] = w
        challenger_arm = min(scores, key=scores.get)

        # Recompute the shared threshold oracle periodically or when leader changes.
        if (oracle is None or n - last_oracle_n >= oracle_period
                or leader != last_oracle_best):
            reg_weight = reg_scale * max(n, 1) ** (-reg_power)
            # Warm-start only if the empirical best arm did not change.
            warm = oracle_z if leader == last_oracle_best else None
            oracle = solve_regularized_shared_qp(
                mle, beta, q_grid, x_grid, reg_weight,
                sigma=sigma, best=leader, x0=warm
            )
            oracle_z = oracle["z"]
            last_oracle_n = n
            last_oracle_best = leader

        # Top-Two arm choice.
        if rng.random() < beta:
            arm = leader
        else:
            arm = challenger_arm

        rho_arm = oracle["rho"][arm]
        q = _sample_from_discrete(rng, q_grid, rho_arm)

        x = streams.sample(arm)
        y = int(x >= q)  # learner observes only y
        qs[arm].append(q)
        ys[arm].append(y)
        counts[arm] += 1
        n += 1

        # Only the sampled arm needs a new MLE.
        mle[arm] = mle_onebit(qs[arm], ys[arm], param_bounds, sigma)

        if n % record_every == 0:
            curr_leader = int(np.argmax(mle))
            glrs = get_pair_glrs(curr_leader)
            history["n"].append(n)
            history["leader"].append(curr_leader)
            history["counts_prop"].append((counts / n).copy())
            history["mle"].append(mle.copy())
            history["min_glr_over_n"].append(min(glrs.values()) / n)
            history["oracle_w"].append(oracle["w"].copy())

    runtime = time.perf_counter() - t0
    return {
        "algorithm": f"onebit-shared-{challenger.upper()}",
        "stopped": stopped,
        "tau": int(n),
        "recommendation": int(recommendation),
        "correct": bool(recommendation == true_best),
        "runtime_sec": float(runtime),
        "counts": counts.copy(),
        "mle": mle.copy(),
        "stopping_stat": float(stopping_stat),
        "history": history,
    }


def run_full_feedback_top_two(
    mu,
    delta=0.05,
    beta=0.5,
    sigma=1.0,
    challenger="TCI",
    max_rounds=20000,
    boundary="common",
    seed=0,
    record_every=25,
):
    """
    Full-feedback Gaussian Top-Two baseline with known common variance.
    It observes X directly, uses empirical means, and the closed-form Gaussian GLR.
    """
    t0 = time.perf_counter()
    rng = np.random.default_rng(seed + 987654321)
    mu = np.asarray(mu, dtype=float)
    streams = GaussianArmStreams(mu, sigma=sigma, seed=seed)
    K = len(mu)
    true_best = int(np.argmax(mu))

    counts = np.zeros(K, dtype=int)
    sums = np.zeros(K, dtype=float)
    means = np.zeros(K, dtype=float)

    n = 0
    for k in range(K):
        x = streams.sample(k)
        counts[k] += 1
        sums[k] += x
        means[k] = sums[k] / counts[k]
        n += 1

    history = {
        "n": [], "leader": [], "counts_prop": [],
        "means": [], "min_glr_over_n": [],
    }

    stopped = False
    recommendation = int(np.argmax(means))
    stopping_stat = 0.0

    while n < max_rounds:
        leader = int(np.argmax(means))
        pair_glr = {
            j: pair_glr_full_gaussian(leader, j, counts, means, sigma)
            for j in range(K) if j != leader
        }
        stopping_stat = min(pair_glr.values())

        # For direct finite-time comparison we default to the same experimental boundary.
        c = common_experimental_boundary(n, delta, K)
        if stopping_stat >= c:
            stopped = True
            recommendation = leader
            break

        scores = {}
        for j, w in pair_glr.items():
            if challenger.upper() == "TCI":
                scores[j] = w + np.log(max(counts[j], 1))
            else:
                scores[j] = w
        challenger_arm = min(scores, key=scores.get)

        arm = leader if rng.random() < beta else challenger_arm
        x = streams.sample(arm)
        counts[arm] += 1
        sums[arm] += x
        means[arm] = sums[arm] / counts[arm]
        n += 1

        if n % record_every == 0:
            curr_leader = int(np.argmax(means))
            glrs = {
                j: pair_glr_full_gaussian(curr_leader, j, counts, means, sigma)
                for j in range(K) if j != curr_leader
            }
            history["n"].append(n)
            history["leader"].append(curr_leader)
            history["counts_prop"].append((counts / n).copy())
            history["means"].append(means.copy())
            history["min_glr_over_n"].append(min(glrs.values()) / n)

    runtime = time.perf_counter() - t0
    return {
        "algorithm": f"full-feedback-{challenger.upper()}",
        "stopped": stopped,
        "tau": int(n),
        "recommendation": int(recommendation),
        "correct": bool(recommendation == true_best),
        "runtime_sec": float(runtime),
        "counts": counts.copy(),
        "means": means.copy(),
        "stopping_stat": float(stopping_stat),
        "history": history,
    }
